import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Pacific Ponds Plus",
//   //,
//   // description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Pacific Ponds Plus</title>
      </head>
      <body>
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
