import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import bg from "../../public/backgroundimage.jpg";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

// export const metadata = {
//   title: "Pacific Ponds Plus",
//   //,
//   // description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>Pacific Ponds Plus</title>
      </head>
      <body>
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
